_wandb:
    value:
        cli_version: 0.23.0
        e:
            3nqjhe9d64ow21brjjv146ju8ml5jth9:
                apple:
                    ecpuCores: 6
                    gpuCores: 18
                    memoryGb: 36
                    name: Apple M3 Pro
                    pcpuCores: 6
                    ramTotalBytes: "38654705664"
                    swapTotalBytes: "9663676416"
                args:
                    - --app
                    - .
                    - --num-supernodes
                    - "10"
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "455732887552"
                email: yanzengyu98@gmail.com
                executable: /opt/miniconda3/envs/sat/bin/python3.12
                host: MAC-F403KFLQW7
                memory:
                    total: "38654705664"
                os: macOS-26.1-arm64-arm-64bit
                program: /opt/miniconda3/envs/sat/bin/flower-simulation
                python: CPython 3.12.12
                root: /Users/zoe.yan/Desktop/repo/hackathons/decentralized/berlin25-eurosat
                startedAt: "2025-11-14T14:02:47.759873Z"
                writerId: 3nqjhe9d64ow21brjjv146ju8ml5jth9
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
            "3":
                - 13
            "4": 3.12.12
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
